maxmemory 512mb
maxmemory-policy allkeys-lru
timeout 0
save 900 1
save 300 10
save 60 10000
tcp-backlog 511
requirepass redis_secure_pass
supervised no
# thread support
io-threads 4
io-threads-do-reads yes